// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKB_qbg6PNSzRINiEuiToT0fjdra5NP9s',
    appId: '1:1033466122569:web:f42d7642f76c7111f04a98',
    messagingSenderId: '1033466122569',
    projectId: 'bangla-typer',
    authDomain: 'bangla-typer.firebaseapp.com',
    storageBucket: 'bangla-typer.firebasestorage.app',
    measurementId: 'G-ZELJQWYK5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQNOVl-EtFZvDHzMxDKdDbC8D6jusMcd0',
    appId: '1:1033466122569:android:cb0cf7635924f0c9f04a98',
    messagingSenderId: '1033466122569',
    projectId: 'bangla-typer',
    storageBucket: 'bangla-typer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-M3n7d61NFEOBIe4N_TPXUnUT23oEkk',
    appId: '1:1033466122569:ios:c52f1f3369ad36e3f04a98',
    messagingSenderId: '1033466122569',
    projectId: 'bangla-typer',
    storageBucket: 'bangla-typer.firebasestorage.app',
    iosBundleId: 'com.arrijal.typer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-M3n7d61NFEOBIe4N_TPXUnUT23oEkk',
    appId: '1:1033466122569:ios:c52f1f3369ad36e3f04a98',
    messagingSenderId: '1033466122569',
    projectId: 'bangla-typer',
    storageBucket: 'bangla-typer.firebasestorage.app',
    iosBundleId: 'com.arrijal.typer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKB_qbg6PNSzRINiEuiToT0fjdra5NP9s',
    appId: '1:1033466122569:web:4c1b6ecfb3d8f9bcf04a98',
    messagingSenderId: '1033466122569',
    projectId: 'bangla-typer',
    authDomain: 'bangla-typer.firebaseapp.com',
    storageBucket: 'bangla-typer.firebasestorage.app',
    measurementId: 'G-2BKQDKL9V3',
  );
}
